name: Run End to End Tests

on: push

jobs:
  run-end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: docker-compose up
          wait-on: "http://localhost"
          wait-on-timeout: 300
          config: baseUrl=http://localhost
          working-directory: web-client
